apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
{{ include "rbac.labels.chart" . | indent 4 }}
{{ include "rbac.labels.stakater" . | indent 4 }}
  name: {{ .Values.ServiceAccountName }}-{{ .Release.Namespace }}-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.ClusterRole }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.ServiceAccountName }}
  namespace: {{ .Release.Namespace }}