apiVersion: v1
name: rbac
version: 1.0.1
appVersion: 1.0.0
description: Chart that deploys PV and PVC for use with any application
keywords:
- pv
- pvc
- kubernetes
home: https://github.com/stakater-charts/rbac
maintainers:
- name: Stakater
  email: stakater@aurorasolutions.io